# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kedinin Adı')),
                ('spec_case', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Durum')),
                ('want_bag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Çanta istiyor mu?')),
                ('spec_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Not')),
                ('name', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('province', models.CharField(max_length=20, verbose_name='İl')),
                ('district', models.CharField(max_length=20, verbose_name='İlçe')),
                ('first_line', models.CharField(max_length=200, verbose_name='Açık Adres')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
