# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ürün Kodu')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name="Birim Fiyatı (KDV'SİZ)")),
                ('price', models.FloatField(verbose_name='Satış Fiyatı')),
                ('vat_rate', models.IntegerField(verbose_name='KDV Oranı')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CategoryModel')),
            ],
        ),
    ]
