# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('ProductCode', models.CharField(max_length=30)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductQuantityType', models.CharField(max_length=30)),
                ('ProductQuantity', models.IntegerField()),
                ('VatRate', models.IntegerField()),
                ('ProductUnitPriceTaxExcluding', models.FloatField()),
                ('ProductUnitPriceTaxIncluding', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Durum')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=20, verbose_name='Metod')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('OrderCode', models.CharField(max_length=10)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('BillingName', models.CharField(max_length=100)),
                ('BillingAddress', models.CharField(max_length=300)),
                ('BillingTown', models.CharField(max_length=30)),
                ('BillingCity', models.CharField(max_length=30)),
                ('BillingMobilePhone', models.CharField(max_length=30)),
                ('ShippingName', models.CharField(max_length=30)),
                ('ShippingAddress', models.CharField(max_length=300)),
                ('ShippingTown', models.CharField(max_length=30)),
                ('ShippingCity', models.CharField(max_length=30)),
                ('Currency', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('TotalPaidTaxExcluding', models.FloatField(verbose_name='Kdv hariç ödenecek toplam tutar')),
                ('TotalPaidTaxIncluding', models.FloatField(verbose_name='Kdv dahil ödenecek toplam tutar')),
                ('ProductsTotalTaxExcluding', models.FloatField(verbose_name='Kdv hariç ürünlerin toplam tutarı')),
                ('ProductsTotalTaxIncluding', models.FloatField(verbose_name='Kdv dahil ürünlerin toplam tutarı')),
                ('OrderDetails', models.ManyToManyField(blank=True, to='api.OrderDetailsModel')),
                ('PaymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PaymentMethods')),
            ],
        ),
    ]
