# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversationId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=100)),
                ('conversationData', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderModel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTransactionId', models.CharField(blank=True, max_length=200, null=True)),
                ('itemId', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('paidPrice', models.FloatField(blank=True, null=True)),
                ('transactionStatus', models.IntegerField(blank=True, null=True)),
                ('blockageRate', models.FloatField(blank=True, null=True)),
                ('blockageRateAmountMerchant', models.FloatField(blank=True, null=True)),
                ('blockageRateAmountSubMerchant', models.FloatField(blank=True, null=True)),
                ('blockageResolvedDate', models.CharField(blank=True, max_length=200, null=True)),
                ('subMerchantPrice', models.FloatField(blank=True, null=True)),
                ('subMerchantPayoutRate', models.FloatField(blank=True, null=True)),
                ('subMerchantPayoutAmount', models.IntegerField(blank=True, null=True)),
                ('iyziCommissionFee', models.FloatField(blank=True, null=True)),
                ('iyziCommissionRateAmount', models.FloatField(blank=True, null=True)),
                ('merchantCommissionRate', models.FloatField(blank=True, null=True)),
                ('merchantCommissionRateAmount', models.FloatField(blank=True, null=True)),
                ('merchantPayoutAmount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandShake',
            fields=[
                ('conversationId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('systemTime', models.BigIntegerField()),
                ('installment', models.IntegerField(blank=True, null=True)),
                ('errorCode', models.CharField(blank=True, max_length=200, null=True)),
                ('errorMessage', models.CharField(blank=True, max_length=200, null=True)),
                ('errorGroup', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('paidPrice', models.FloatField(blank=True, null=True)),
                ('basketId', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('binNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('lastFourDigits', models.CharField(blank=True, max_length=200, null=True)),
                ('cardAssociation', models.CharField(blank=True, max_length=200, null=True)),
                ('cardFamily', models.CharField(blank=True, max_length=200, null=True)),
                ('cardType', models.CharField(blank=True, max_length=200, null=True)),
                ('authCode', models.CharField(blank=True, max_length=200, null=True)),
                ('phase', models.CharField(blank=True, max_length=200, null=True)),
                ('mdStatus', models.IntegerField()),
                ('hostReference', models.CharField(blank=True, max_length=200, null=True)),
                ('fraudStatus', models.BooleanField(blank=True, null=True)),
                ('iyziCommissionFee', models.FloatField(blank=True, null=True)),
                ('iyziCommissionRateAmount', models.FloatField(blank=True, null=True)),
                ('merchantCommissionRate', models.FloatField(blank=True, null=True)),
                ('merchantCommissionRateAmount', models.FloatField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Conversation')),
                ('itemTransactions', models.ManyToManyField(to='paymentapp.ItemTransactions')),
            ],
        ),
    ]
