# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Konu')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bildirim Başlığı')),
                ('content', models.CharField(max_length=200, verbose_name='Bildirim İçeriği')),
                ('code', models.CharField(max_length=100, verbose_name='Bildirim Kodu')),
                ('time', models.DateTimeField(verbose_name='Tarih')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification_Subject', verbose_name='Konu')),
            ],
        ),
    ]
