# Generated by Django 3.0.2 on 2020-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Kullanıcın kargoya vermesi bekleniyor.'), ('1', 'Kutunun satıcıya ulaşması bekleniyor.'), ('2', 'Satıcı onayı bekleniyor.'), ('3', 'Onaylandı. En kısa sürede ücret iadesi yapılacak.'), ('4', 'Reddedildi kutu tekrar müşteriye gönderiliyor.'), ('5', 'İade işlemi tamamlandı.')], max_length=20, verbose_name='Durum')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Tutar')),
                ('payment', models.BooleanField(verbose_name='Ödeme Durumu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('deliveryDate', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('order_type', models.CharField(choices=[('0', 'Abonelik'), ('1', 'Hediye')], max_length=8, verbose_name='Sipariş Türü')),
                ('status', models.CharField(choices=[('0', 'Ödeme Onayı Bekleniyor'), ('1', 'Sipariş Hazırlanıyor'), ('2', 'Sipariş Kargoda'), ('3', 'Ödeme Hatası'), ('10', 'Sipariş Tamamlandı'), ('20', 'İptal talep edildi.'), ('21', 'İptal Onaylandı.'), ('22', 'İptal Reddedildi.')], max_length=30, verbose_name='Sipariş Durumu')),
                ('cargo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Takip Kodu')),
                ('fail_message', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hata Mesajı')),
                ('referenceCode', models.CharField(max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('retry_message', models.CharField(blank=True, max_length=250, null=True)),
                ('birfatura_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Orders')),
                ('products', models.ManyToManyField(to='product.ProductModel')),
            ],
        ),
    ]
